name: Update README with GitHub Top Languages

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC (adjust as needed)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: macos-latest  # Use macOS runner instead of Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch Top Languages image and update README.md
        run: |
          set -e  # Stop if any command fails
          echo "Fetching top languages..."
          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=VuthChanChesda&layout=compact&theme=radical&token=${{ secrets.GH_TOKEN }}" > top-langs-image.svg
          
          # Debugging: Output fetched image content to the log
          cat top-langs-image.svg

          # Update README.md with the new image
          sed -i '' '/Top Languages/ {n;s|![^ ]*|![Top Languages](top-langs-image.svg)|}' README.md

          # Debugging: Ensure the update happened
          echo "README updated with top languages image."

      - name: Commit and push changes to README.md
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add README.md
          
          # Log any differences before committing
          git diff README.md

          git commit -m "Update Top Languages in README.md"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's default token
