name: Update README with GitHub Top Languages

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC (adjust as needed)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: macos-latest  # Use macOS runner for compatibility
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch Top Languages image and update README.md
        run: |
          set -e
          echo "Fetching top languages..."
          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=VuthChanChesda&layout=compact&theme=radical&token=${{ secrets.GH_TOKEN }}" > top-langs-image.svg
          cat top-langs-image.svg  # Debugging step to view image data
          # Replacing old image URL with new one in README.md
          awk '/Top Languages/ { print; print "!["Top Languages"](top-langs-image.svg)"; next }1' README.md > tmpfile && mv tmpfile README.md
          echo "README updated"

      - name: Commit and push changes to README.md
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add README.md
          git diff README.md  # Show the diff to verify changes
          git commit -m "Update Top Languages in README.md"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/VuthChanChesda/VuthChanChesda.git
