name: Update README with GitHub Top Languages

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC (adjust as needed)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Fetch Top Languages image and update README.md
        run: |
          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=VuthChanChesda&layout=compact&theme=radical&token=${{ secrets.GH_TOKEN }}" > top-langs-image.svg
          sed -i '/Top Languages/ {n;s|![^ ]*|![Top Languages](top-langs-image.svg)|}' README.md

      - name: Commit and push changes to README.md
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update Top Languages in README.md"
          git push
